name: Testing

on: [push]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run doctests
      run: |
        python -m doctest 2023/*.py
    - name: Run static type check
      run: |
        python -m mypy --ignore-missing-imports 2023/*.py
    - name: Check format
      uses: psf/black@stable
      with:
        options: "--check --verbose"
        src: "2023/*.py"