name: Testing

on: [push]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run doctests
      run: |
        python -m doctest 2022/*.py
    - name: Run static type check
      run: |
        python -m mypy --ignore-missing-imports 2022/*.py